### ISSUE TITLE
Login and Security

### ISSUE THREAD

**Issue by Kevinayad** [DIT112-V21/group-04#33]
User Story: 
As a medical worker, I want a login system with personal login details in order to ensure a more secure system not allowing outside users to disturb our cars.

Acceptance criteria: 
When entering the app a login screen with login verification should be displayed to the user.

**Comment by Arunjazz** [comment]
Hey , may i join this project

**Comment by platisd** [comment]
> Hey , may i join this project

@Arunjazz interesting question! This is part of a university course ([DIT112](https://canvas.gu.se/courses/42674/assignments/syllabus) @ Gothenburg University, Sweden) so naturally you cannot participate in the course itself, but since this is an open source project there's nothing stopping you from talking to the team and/or submitting pull requests.

**Comment by MarkusJ299** [comment]
Closing this issue. It is out of scope due to time constraints.
